name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run tests and generate traces
      run: |
        pytest --tracing=retain-on-failure
        mkdir -p test-results/
        mv trace.zip test-results/
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: test-results/
